StatCan/jupyter-apis

README.md

Resolves https://github.com/StatCan/jupyter-apis/issues/8 and https://github.com/StatCan/jupyter-apis/issues/10

docs: update README for local development

---

frontend/package-lock.json
frontend/package.json
frontend/src/app/resource-form/resource-form.component.ts

Resolves https://github.com/StatCan/jupyter-apis/issues/22
update @angular-devkit/build-angular to version 0.1001.2 to resolve:
*node-forge (CVE-2020-7720)
*yargs-parser (GHSA-p9pc-299p-vxgp)
*http-proxy (GHSA-6x33-pw7p-hmpq)
*tree-kill (GHSA-884p-74jh-xrg2)
update node-sass to 4.14.1 (GHSA-9v62-24cr-58cx)
Also resolves https://github.com/StatCan/jupyter-apis/issues/24

fix: resolve dependabot alerts

---

frontend/src/app/main-table/cost-table/cost-table.component.html
frontend/src/app/main-table/cost-table/cost-table.component.scss
frontend/src/app/main-table/cost-table/cost-table.component.ts
frontend/src/app/main-table/main-table.component.html
frontend/src/app/main-table/main-table.component.ts
frontend/src/app/main-table/volumes-table/volume-table.component.html
frontend/src/app/main-table/volumes-table/volume-table.component.ts
frontend/src/app/services/kubecost.service.ts
frontend/src/assets/i18n/en.json
frontend/src/assets/i18n/fr.json

Resolves https://github.com/StatCan/jupyter-apis/issues/33
- Checks to see if response from API is not empty
- Fix cost table message to be more descriptive (over the last 24 hours instead of per day) as it is confusing to some users

fix: add check for empty response

---

frontend/src/app/resource-form/form-gpus/form-gpus.component.html
frontend/src/app/resource-form/form-gpus/form-gpus.component.ts
frontend/src/app/resource-form/form-specs/form-specs.component.html
frontend/src/app/resource-form/form-specs/form-specs.component.ts
frontend/src/app/resource-form/resource-form.component.html
frontend/src/app/resource-form/resource-form.component.ts
frontend/src/assets/i18n/en.json
frontend/src/assets/i18n/fr.json

Resolves https://github.com/StatCan/jupyter-apis/issues/37
Wasn't sure if we want it as an error if the user doesn't enter the max CPU/RAM numbers if 1 GPU is selected or if we want to grey out the input areas for CPU/RAM and set it as a default? 
For now, did it as part of the error check so the user is aware they are booking the entire machine.

fix: add cpu/ram max requirement for 1 gpu (frontend) + translation

---

frontend/src/app/resource-form/volume/volume.component.html
frontend/src/app/resource-form/volume/volume.component.ts
frontend/src/assets/i18n/en.json
frontend/src/assets/i18n/fr.json

Resolves https://github.com/StatCan/jupyter-apis/issues/50

feat: Add validation for mounted pvc

---

frontend/src/app/resource-form/resource-form.component.ts
frontend/src/assets/i18n/en.json
frontend/src/assets/i18n/fr.json

My colleague's GPU image was not able to be scheduled, it appears because of the CPU limits. After doing a few `kubectl edit`s on his image, adjusting the cpu and memory, I found that reducing the CPU without touching the memory was enough to get the image scheduled.

fix: lower gpu node cpu-request to allow scheduling

---

frontend/src/app/resource-form/form-image/form-image.component.html
frontend/src/app/resource-form/form-image/form-image.component.ts
frontend/src/assets/i18n/en.json
frontend/src/assets/i18n/fr.json

fix: add url validation for custom images

---

notebooks.go

A bit hard to test locally, but I did something like 
and it worked out fine adding the label

fix(use the better label)

---

frontend/jupyter/src/app/pages/form/form-default/form-advanced-options/form-advanced-options.component.html
frontend/jupyter/src/app/pages/form/form-default/form-advanced-options/form-advanced-options.component.ts
frontend/jupyter/src/app/pages/form/form-default/utils.ts

Implements changes introduced by [feat: Add env variable to set language of the notebook server](https://github.com/StatCan/jupyter-apis/pull/48/commits/83af67391be036d279453a649bb5b6a9f08a985b) to be compatible with KF 1.3 front end. EXCLUDES ANY i18n which will be addressed in https://github.com/StatCan/jupyter-apis/issues/73
Closes #74

feat: add KF_LANG env variable

---

frontend/jupyter/src/app/pages/form/form-default/volume/volume.component.html
frontend/jupyter/src/app/pages/index/index-default/index-default.component.html
frontend/jupyter/src/assets/i18n/en.json
frontend/jupyter/src/assets/i18n/fr.json

Remove kubecost table and fix i18n

---

.github/workflows/publish.yml
frontend/jupyter/src/app/pages/form/form-default/form-image/form-image.component.ts
notebooks.go

Closes https://github.com/StatCan/daaas/issues/1078
Previously was not being handled.
Can test this right now on dev if you want

feat(imagePullPolicy): Add and set it

---

samples/spawner_ui_config.yaml

Change `employee-only-features` label to `state.aaw.statcan.gc.ca/exists-non-sas-notebook-user` in `spawner_ui_config.yaml` to grey out SAS icon if there exists a user in the namespace without the SAS notebook capability.

feat: non-employee-rbac

---

frontend/common/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/status/types.ts
frontend/common/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/types/status.ts
frontend/jupyter/package.json
frontend/jupyter/src/app/pages/index/index-default/config.ts
frontend/jupyter/src/app/pages/index/index-default/index-default.component.html
frontend/jupyter/src/app/pages/index/index-default/index-default.component.ts
frontend/jupyter/src/app/services/backend.service.ts
frontend/jupyter/src/app/types/responses.ts
frontend/jupyter/src/app/types/volume/interfaces.ts
frontend/jupyter/tsconfig.json

closes #139 
To test, just run locally following the readme, and you should see the volume table.

Fix 139 add volume table

---

frontend/common/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/paginator/paginator.component.ts
frontend/common/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/resource-table.module.ts
frontend/common/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/status/types.ts
frontend/jupyter/i18n/fr/messages.fr.xlf
frontend/jupyter/i18n/messages.xlf
frontend/jupyter/src/app/pages/form/form-default/form-configurations/form-configurations.component.html
frontend/jupyter/src/app/pages/form/form-default/form-cpu-ram/form-cpu-ram.component.html
frontend/jupyter/src/app/pages/form/form-default/form-default.component.html
frontend/jupyter/src/app/pages/form/form-default/form-gpus/form-gpus.component.html
frontend/jupyter/src/app/pages/form/form-default/form-gpus/form-gpus.component.ts
frontend/jupyter/src/app/pages/form/form-default/form-image/form-image.component.html
frontend/jupyter/src/app/pages/form/form-default/volume/existing/pvc/pvc.component.html
frontend/jupyter/src/app/pages/index/index-default/index-default.component.ts
frontend/jupyter/src/app/shared/utils/volumes/panel.ts
notebooks.go

closes #160 
To test, instead of doing the npm start, do npm run start:fr when booting the frontend to boot it in french

Update 1.6 translation files

---

config.go
frontend/common/kubeflow-common-lib/projects/kubeflow/src/lib/services/namespace.service.ts
frontend/jupyter/src/app/pages/form/form-default/form-data-volumes/form-data-volumes.component.ts
frontend/jupyter/src/app/pages/form/form-default/utils.ts
frontend/jupyter/src/app/pages/form/form-default/volume/new/access-modes/access-modes.component.html
frontend/jupyter/src/app/pages/form/form-default/volume/new/new.component.html
frontend/jupyter/src/app/pages/form/form-default/volume/new/storage-class/storage-class.component.html
frontend/jupyter/src/app/shared/utils/volumes/forms.ts
notebooks.go
samples/spawner_ui_config.yaml

Fix volumes let people submit their workload requests
closes https://github.com/StatCan/jupyter-apis/issues/158

1.6 fix volumes

---

frontend/jupyter/src/app/pages/form/form-default/form-default.component.html

fix(volume name): update formCtrl.get() to formCtrl.get().value.
The Angular code for `<app-form-data-volumes>` was missing `.value`, I just needed to add it. :-)

fix(volume name): update formCtrl.get()

---

frontend/jupyter/src/app/pages/form/form-default/volume/new/size/size.component.ts

closes #108 
Setting `this.sizeNum.setValue("16");` in `ngOnInit()` of `size.component.ts` sets the default value in `mat-select` of `size.component.html` to `16`.
- https://stackoverflow.com/questions/50650790/set-default-option-in-mat-select

set(sizeNum): default to 16

---

frontend/jupyter/src/app/pages/index/index-default/index-default.component.html

Closes https://github.com/StatCan/jupyter-apis/issues/176
Simple fix, remove the css that made the tables in Notebooks scrollable

JWA: Fix css table

---

notebooks.go

Was preventing users from creating notebooks without a volume
closes https://github.com/StatCan/jupyter-apis/issues/172

fix(notebook): remove else preventing no volumes

---

frontend/jupyter/src/app/pages/form/form-default/form-default.component.ts

When the user toggles the GPU settings, the CPU and memory settings now returns to 1 CPU and 4 gigabyes of ram, which is a usable state.
Closes #178.

update(form-default): return to usable state.

---

frontend/jupyter/src/app/pages/index/index-default/config.ts
frontend/jupyter/src/app/pages/index/index-default/index-default.component.html
frontend/jupyter/src/app/pages/index/index-default/index-default.component.spec.ts
frontend/jupyter/src/app/pages/index/index-default/index-default.component.ts
frontend/jupyter/src/app/pages/index/index-rok/index-rok.component.spec.ts
frontend/jupyter/src/app/pages/index/index-rok/index-rok.component.ts
frontend/jupyter/src/app/pages/index/index.component.spec.ts

for https://github.com/StatCan/jupyter-apis/issues/218
Added the file index-default.component.ts in the [i18n ticket](https://github.com/StatCan/jupyter-apis/issues/221) since there are some new text in there

Kf1.7 jupyter apis index frontend

---

frontend/jupyter/src/styles.scss

for https://github.com/StatCan/jupyter-apis/issues/256
The reason the css change is in the general styles.scss file and not inside the form-image.component.scss that relates directly to this component is because the html elements that needed to be styled are auto-generated by the angular component mat-button-toggle. When specifying the style in the form-image css file, the styling was not being applied.

added style to fix server image button bug

---

.github/workflows/build.yml
.github/workflows/publish.yml

Related to https://github.com/StatCan/aaw-private/issues/112
WIP.
I think the duplication of work that is being seen is because the `build.yml` used to be for PR's and would just build on that, but since we changed our `publish.yml` to also account for PRs with the `auto-deploy` tag (which in the majority of cases we want) it looks like a duplication of work which came from this [pr](https://github.com/StatCan/jupyter-apis/commit/51c6c44b92e752a456719e7c8d2878a06bd750bb) where we added the ability to push to dev acr using the tag.
It wouldn't be a duplication of work if the PR doesnt have the `auto-deploy` tag on, it would just `build`. 
So perhaps a good in-between would be to have the `build.yml` workflow run only if the `auto-deploy` tag isn't on it.

chore(scanning): migrate from azure container scan to trivy

---

.github/workflows/publish.yml
frontend/jupyter/package-lock.json
frontend/jupyter/package.json
frontend/jupyter/yarn.lock

for https://jirab.statcan.ca/browse/BTIS-390

Replaced Dockle with hadolint

---

frontend/jupyter/cypress/e2e/form-page.cy.ts
frontend/jupyter/cypress/support/commands.ts
frontend/jupyter/cypress/support/e2e.ts
frontend/jupyter/src/app/pages/form/form-new/form-cpu-ram/form-cpu-ram.component.ts
frontend/jupyter/src/app/pages/form/form-new/form-new.component.html
frontend/jupyter/src/app/pages/form/form-new/form-new.component.ts

Closes https://jirab.statcan.ca/browse/BTIS-409

chore(jupyter): Remove GPU from form

---

frontend/common/kubeflow-common-lib/projects/kubeflow/src/lib/form/section/section.component.html
frontend/common/kubeflow-common-lib/projects/kubeflow/src/lib/title-actions-toolbar/title-actions-toolbar.component.html
frontend/common/kubeflow-common-lib/projects/kubeflow/src/styles/styles.scss
frontend/jupyter/src/app/pages/index/index-default/config.ts
frontend/jupyter/src/app/pages/notebook-page/notebook-page.component.html
frontend/jupyter/src/app/pages/volume-details-page/volume-details-page.component.html
frontend/jupyter/src/styles.scss

See https://jirab.statcan.ca/browse/BTIS-882

Kf1.9(jupyter): fix style

---

notebooks.go

Former condition messages in the notebook condition tables were very technical and unhelpful for the end user, this change provides a new function to transform the messages to user friendly ones, otherwise, it falls back to the default message provided by the k8s api.
Details about Notebook Conditions can be found here: https://www.kubeflow.org/docs/components/notebooks/api-reference/notebook-v1/#kubeflow.org/v1.NotebookCondition
NOTE: This ticket does not add friendly error message, it provides a feature (translate function) to turn technical messages into end user friendly ones.
Before: 
After: 
Create a Notebook with high allocated resources (ie lots of ram and cpu), when the notebook errors, click on it and check the message like you can see below:
What types of changes does your code …

fix(notebooks.go): transform condition messages
