StatCan/jupyter-apis

main.go

Fix limit local dev deployment

---

Dockerfile

Resolves https://github.com/StatCan/kubeflow-manifest/issues/39
Related to https://github.com/StatCan/kubeflow-manifest/pull/40#pullrequestreview-487879762

fix(Dockerfile): add env variable

---

frontend/.prettierrc
frontend/src/app/resource-form/form-data-volumes/form-data-volumes.component.html
frontend/src/app/resource-form/form-name/form-name.component.html
frontend/src/app/resource-form/form-name/form-name.component.ts
frontend/src/app/resource-form/form-specs/form-specs.component.html
frontend/src/app/resource-form/form-specs/form-specs.component.ts
frontend/src/app/resource-form/form-workspace-volume/form-workspace-volume.component.html
frontend/src/app/resource-form/volume/volume.component.html
frontend/src/app/resource-form/volume/volume.component.ts
frontend/src/app/utils/common.ts
samples/spawner_ui_config.yaml

Resolves https://github.com/StatCan/jupyter-apis/issues/7

Notebook server validation

---

frontend/src/app/resource-form/form-data-volumes/form-data-volumes.component.html
frontend/src/app/resource-form/form-data-volumes/form-data-volumes.component.scss
frontend/src/app/resource-form/volume/volume.component.scss

Adjusts styles so that new data volumes in the "new server" view
display their fields correctly.
Fixes #28

fix: Improve spacing for new data volume config

---

frontend/src/app/resource-form/form-specs/form-specs.component.ts

Resolves https://github.com/StatCan/jupyter-apis/issues/36

fix: update ram limits

---

frontend/src/assets/i18n/en.json
frontend/src/assets/i18n/fr.json

Resolves https://github.com/StatCan/jupyter-apis/issues/39

fix: kubecost table message

---

notebooks.go

Resolves https://github.com/StatCan/daaas/issues/339
Not fully able to test this yet as I don't have access to the dev cluster at the moment.

fix: add check for runnning notebook server

---

frontend/src/app/resource-form/form-advanced-options/form-advanced-options.component.html
frontend/src/app/resource-form/form-advanced-options/form-advanced-options.component.scss
frontend/src/app/resource-form/form-advanced-options/form-advanced-options.component.ts
frontend/src/app/utils/common.ts
frontend/src/assets/i18n/en.json
frontend/src/assets/i18n/fr.json
go.sum
notebooks.go

Resolves https://github.com/StatCan/jupyter-apis/issues/47

feat: add KF_LANG env variable

---

frontend/src/app/resource-form/form-image/form-image.component.html
frontend/src/assets/i18n/en.json
frontend/src/assets/i18n/fr.json

Resolves https://github.com/StatCan/daaas/issues/358
to be merged after PR https://github.com/StatCan/daaas/pull/491

feat: url link to image info page

---

notebooks.go

Add a label indicating that the volume is protected b
iff notebook.Labels[notebook.statcan.gc.ca/protected-b] exists
Closes #62

fix(prob volumes)

---

notebooks.go

Add pvc volume "data.statcan.gc.ca/classification": "protected-b" to pro b notebook.

add: prob volume label

---

frontend/jupyter/src/app/app.module.ts
frontend/jupyter/src/app/pages/form/form-default/volume/volume.component.html
frontend/jupyter/src/app/pages/form/form-default/volume/volume.component.ts
frontend/jupyter/src/app/services/backend.service.ts
frontend/jupyter/src/app/services/namespace.service.spec.ts
frontend/jupyter/src/app/services/namespace.service.ts
frontend/jupyter/src/app/types.ts

Feat volume validation

---

config.go
frontend/common/kubeflow-common-lib/projects/kubeflow/src/lib/form/form.module.ts
frontend/common/kubeflow-common-lib/projects/kubeflow/src/lib/form/section-image/section.image.component.html
frontend/common/kubeflow-common-lib/projects/kubeflow/src/lib/form/section-image/section.image.component.scss
frontend/common/kubeflow-common-lib/projects/kubeflow/src/lib/form/section-image/section.image.component.spec.ts
frontend/common/kubeflow-common-lib/projects/kubeflow/src/lib/form/section-image/section.image.component.ts
frontend/jupyter/package.json
frontend/jupyter/proxy.config.js
frontend/jupyter/src/app/pages/form/form-default/form-default.component.html
frontend/jupyter/src/app/pages/form/form-default/form-image/form-image.component.html
frontend/jupyter/src/app/pages/form/form-default/form-image/form-image.component.ts
frontend/jupyter/src/app/types.ts
samples/spawner_ui_config.yaml

feat-custom-url validation

---

frontend/jupyter/src/app/pages/form/form-default/form-cpu-ram/form-cpu-ram.component.html
frontend/jupyter/src/app/pages/form/form-default/form-cpu-ram/form-cpu-ram.component.ts

Add custom validation for cpu/ram limits

feat(frontend):add cpu,ram limits validation

---

frontend/jupyter/src/app/pages/form/form-default/volume/volume.component.html
frontend/jupyter/src/app/pages/form/form-default/volume/volume.component.ts
frontend/jupyter/src/app/services/backend.service.ts
frontend/jupyter/src/app/types.ts

feat: volume-validation

---

frontend/common/kubeflow-common-lib/projects/kubeflow/src/assets/en.json
frontend/common/kubeflow-common-lib/projects/kubeflow/src/assets/fr.json
frontend/jupyter/src/app/pages/form/form-default/form-advanced-options/form-advanced-options.component.html
frontend/jupyter/src/app/pages/form/form-default/form-advanced-options/form-advanced-options.component.ts
frontend/jupyter/src/app/pages/form/form-default/form-default.component.ts
frontend/jupyter/src/app/types.ts
frontend/jupyter/src/assets/en.json
frontend/jupyter/src/assets/fr.json

Add missing kflang components and i18n text

feat(kflang):add kflang components

---

frontend/jupyter/src/app/pages/form/form-default/volume/volume.component.ts
frontend/jupyter/src/assets/i18n/en.json
frontend/jupyter/src/assets/i18n/fr.json

Add i18n for volume validation

add(i18n):volume validation

---

frontend/common/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/status/status.component.html
frontend/jupyter/src/app/pages/index/index-default/index-default.component.ts
frontend/jupyter/src/app/types.ts
notebooks.go

Fix status of both Notebook and Volume statuses

fix: missing key in status of notebook

---

frontend/jupyter/src/app/pages/form/form-default/form-cpu-ram/form-cpu-ram.component.ts

feat: change cpu limit

---

frontend/jupyter/src/app/pages/form/form-default/form-image/form-image.component.ts
frontend/jupyter/src/app/pages/form/form-default/utils.ts
samples/spawner_ui_config.yaml

By default change to always to ease restarting images
to get the latest updates
I believe this is needed
I cannot seem to get it to be "Always" https://github.com/StatCan/daaas/issues/1078

feat(imagePullPolicy): Change to Always

---

README.md
frontend/jupyter/src/app/pages/index/index-default/index-default.component.html
frontend/jupyter/src/app/pages/index/index-default/index-default.component.ts
frontend/jupyter/src/app/types.ts

closes https://github.com/StatCan/jupyter-apis/issues/123

fixed kubecost table

---

frontend/common/kubeflow-common-lib/projects/kubeflow/src/lib/form/form.module.ts
frontend/common/kubeflow-common-lib/projects/kubeflow/src/lib/form/section-image/section.image.component.html
frontend/common/kubeflow-common-lib/projects/kubeflow/src/lib/form/section-image/section.image.component.scss
frontend/common/kubeflow-common-lib/projects/kubeflow/src/lib/form/section-image/section.image.component.spec.ts
frontend/common/kubeflow-common-lib/projects/kubeflow/src/lib/form/section-image/section.image.component.ts
frontend/common/kubeflow-common-lib/projects/kubeflow/src/public-api.ts
frontend/jupyter/src/app/pages/form/form-default/form-advanced-options/form-advanced-options.component.html
frontend/jupyter/src/app/pages/form/form-default/form-affinity-tolerations/form-affinity-tolerations.component.html
frontend/jupyter/src/app/pages/form/form-default/form-configurations/form-configurations.component.html
frontend/jupyter/src/app/pages/form/form-default/form-cpu-ram/form-cpu-ram.component.html
frontend/jupyter/src/app/pages/form/form-default/form-data-volumes/form-data-volumes.component.html
frontend/jupyter/src/app/pages/form/form-default/form-gpus/form-gpus.component.html
frontend/jupyter/src/app/pages/form/form-default/form-image/form-image.component.html
frontend/jupyter/src/app/pages/form/form-default/form-name/form-name.component.html
frontend/jupyter/src/app/pages/form/form-default/form-workspace-volume/form-workspace-volume.component.html

Fix 136 add hint text

---

frontend/jupyter/src/app/pages/form/form-default/form-default.component.html
frontend/jupyter/src/app/pages/form/form-default/form-default.component.ts
frontend/jupyter/src/app/pages/form/form-default/form-image/form-image.component.html
frontend/jupyter/src/app/pages/form/form-default/form-image/form-image.component.scss
frontend/jupyter/src/app/pages/form/form-default/form-image/form-image.component.ts
frontend/jupyter/src/app/pages/form/form-default/utils.ts
frontend/jupyter/src/app/pages/form/form-rok/form-rok.component.html
frontend/jupyter/src/app/pages/index/index-default/server-type/server-type.component.html
frontend/jupyter/src/app/pages/index/index-default/server-type/server-type.component.ts
frontend/jupyter/src/app/services/backend.service.ts
frontend/jupyter/src/app/types/config.ts
frontend/jupyter/src/app/types/notebook.ts
frontend/jupyter/src/app/types/responses.ts
frontend/jupyter/src/environments/environment.prod.ts
frontend/jupyter/src/environments/environment.rok.prod.ts
frontend/jupyter/src/environments/environment.rok.ts
frontend/jupyter/src/environments/environment.ts
samples/spawner_ui_config.yaml

1.6 update - add sass

---

frontend/jupyter/src/app/pages/form/form-default/utils.ts

Fix 142 image pull policy + fix

---

frontend/jupyter/src/app/pages/form/form-default/form-advanced-options/form-advanced-options.component.html
frontend/jupyter/src/app/pages/form/form-default/form-advanced-options/form-advanced-options.component.scss
frontend/jupyter/src/app/pages/form/form-default/form-advanced-options/form-advanced-options.component.ts
frontend/jupyter/src/app/pages/form/form-default/utils.ts

Fix 134 add environment variable

---

frontend/jupyter/src/app/pages/form/form-default/form-cpu-ram/form-cpu-ram.component.html
frontend/jupyter/src/app/pages/form/form-default/form-cpu-ram/form-cpu-ram.component.ts
frontend/jupyter/src/app/pages/form/form-default/form-default.component.html
frontend/jupyter/src/app/pages/form/form-default/form-default.component.ts
frontend/jupyter/src/app/pages/form/form-default/form-gpus/form-gpus.component.html
frontend/jupyter/src/app/pages/form/form-default/form-gpus/form-gpus.component.ts
frontend/jupyter/yarn.lock

modify limits, gpus and cpus

---

frontend/jupyter/src/app/pages/form/form-default/form-default.component.ts
frontend/jupyter/src/app/pages/form/form-rok/form-rok.component.ts

1.6 - fix miscellaneous

---

main.go
storageclasses.go

added missing api endpoint for getting storage classes

---

Dockerfile

Nginx will listen on original upstream port and golang API listens on new port

refactor(Dockerfile): bind API to new port

---

frontend/common/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/action/action.component.html

fixed action icon button tooltip

---

config.go
frontend/common/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/action/action.component.html
frontend/jupyter/src/app/pages/index/index-default/config.ts
frontend/jupyter/src/app/pages/index/index-default/index-default.component.ts
frontend/jupyter/src/app/pages/index/index-default/protb-icon/protb-icon.component.html
frontend/jupyter/src/app/pages/index/index-default/protb-icon/protb-icon.component.ts
frontend/jupyter/src/app/pages/index/index.module.ts
frontend/jupyter/src/app/types/notebook.ts
frontend/jupyter/src/app/types/volume/interfaces.ts
notebooks.go
persistentvolumeclaims.go

closes https://github.com/StatCan/daaas/issues/629

added Pro b icon

---

frontend/jupyter/src/app/pages/form/form-default/form-advanced-options/form-advanced-options.component.ts

closes https://github.com/StatCan/daaas/issues/1310

added current language context to system language input

---

frontend/jupyter/i18n/fr/messages.fr.xlf
frontend/jupyter/i18n/messages.xlf
frontend/jupyter/src/app/pages/form/form-default/form-cpu-ram/form-cpu-ram.component.ts
frontend/jupyter/src/app/pages/form/form-default/form-image/form-image.component.ts
frontend/jupyter/src/app/pages/form/form-default/volume/new/name/name.component.ts

updated translations

---

notebooks.go

fix(volumes): don't append volume spec when none requested

---

frontend/jupyter/i18n/fr/messages.fr.xlf
frontend/jupyter/i18n/messages.xlf
frontend/jupyter/src/app/pages/index/index-default/index-default.component.html

Closes https://github.com/StatCan/daaas/issues/1454

Add text to the cost

---

frontend/jupyter/i18n/fr/messages.fr.xlf
frontend/jupyter/i18n/messages.xlf
frontend/jupyter/src/app/pages/form/form-default/form-cpu-ram/form-cpu-ram.component.html
frontend/jupyter/src/app/pages/form/form-default/form-cpu-ram/form-cpu-ram.component.ts
frontend/jupyter/src/app/pages/form/form-default/volume/new/name/name.component.ts

closes https://github.com/StatCan/jupyter-apis/issues/189

Validation bugs in the new notebook form

---

.github/workflows/publish.yml
README.md

Add conditional push on pull request with auto-deploy
Related to https://github.com/StatCan/daaas/issues/1410

feat: add workflow for auto-deploy tag

---

frontend/jupyter/src/app/pages/form/form-default/form-cpu-ram/form-cpu-ram.component.ts
frontend/jupyter/src/app/pages/form/form-default/form-default.component.ts
k8s/manifests/configs/spawner_ui_config.yaml
samples/spawner_ui_config.yaml

fix for https://github.com/StatCan/daaas/issues/1479

Cpu memory limit bug

---

frontend/jupyter/i18n/fr/messages.fr.xlf
frontend/jupyter/i18n/messages.xlf
frontend/jupyter/src/app/pages/form/form-default/form-cpu-ram/form-cpu-ram.component.ts

closes https://github.com/StatCan/jupyter-apis/issues/191

added validator for resource limits

---

frontend/jupyter/src/app/pages/form/form-default/form-data-volumes/form-data-volumes.component.html
frontend/jupyter/src/app/pages/form/form-default/form-workspace-volume/form-workspace-volume.component.html
frontend/jupyter/src/app/pages/form/form-default/volume/existing/existing-volume.component.html
frontend/jupyter/src/app/pages/form/form-default/volume/new/new.component.html

closes https://github.com/StatCan/jupyter-apis/issues/196

ui enhancement removed volume type field

---

.github/workflows/publish.yml
frontend/jupyter/src/app/pages/index/index-default/index-default.component.html

closes https://github.com/StatCan/daaas/issues/1382 to push to the dev acr with pull requests that have the auto-deploy label

added push to dev acr on pull request

---

config.go
frontend/jupyter/src/app/pages/form/form-default/form-cpu-ram/form-cpu-ram.component.ts
frontend/jupyter/src/app/pages/form/form-default/form-default.component.ts
frontend/jupyter/src/app/types/config.ts
samples/spawner_ui_config.yaml

closes https://github.com/StatCan/daaas/issues/1562

added defaults to config for when gpu changes value

---

notebooks.go

Add automount label. Apart of blob-csi mutating webhook logic

append: blob mount annotation

---

frontend/jupyter/src/app/pages/form/form-default/form-image/form-image.component.html

closes https://github.com/StatCan/daaas/issues/1551
Commented out instead of full out deleting to help while rebasing so that we don't accidentally put it back it

removed the advanced options for image section

---

.github/workflows/frontend_tests.yml
README.md
frontend/jupyter/package-lock.json
frontend/jupyter/package.json
frontend/jupyter/yarn.lock

closes https://github.com/StatCan/jupyter-apis/issues/209

adding frontend tests workflow

---

frontend/jupyter/i18n/fr/messages.fr.xlf
frontend/jupyter/i18n/messages.xlf
frontend/jupyter/src/app/pages/form/form-default/volume/mount/mount.component.html
frontend/jupyter/src/app/pages/form/form-default/volume/mount/mount.component.ts

Closes https://github.com/StatCan/daaas-private/issues/71

Feat mount path validation

---

frontend/common/kubeflow-common-lib/angular.json
frontend/jupyter/angular.json
frontend/jupyter/i18n/fr/messages.fr.xlf
frontend/jupyter/i18n/messages.xlf
frontend/jupyter/src/app/pages/index/index-default/config.ts
frontend/jupyter/src/app/pages/index/index-default/index-default.component.ts
frontend/jupyter/src/app/services/kubecost.service.ts
frontend/jupyter/src/app/types/allocationcost.ts
frontend/jupyter/yarn.lock
namespacecost.go

for https://github.com/StatCan/daaas/issues/1657

added shared cost column

---

frontend/jupyter/src/app/pages/index/index-default/config.ts
frontend/jupyter/src/app/pages/index/index-default/index-default.component.ts

Hides the shared cost column at Charles' request (no github issue related)

commented out shared cost column

---

frontend/jupyter/src/app/pages/volume-details-page/events/config.ts
frontend/jupyter/src/app/pages/volume-details-page/events/events.component.html
frontend/jupyter/src/app/pages/volume-details-page/events/events.component.spec.ts
frontend/jupyter/src/app/pages/volume-details-page/events/events.component.ts
frontend/jupyter/src/app/pages/volume-details-page/events/events.module.ts
frontend/jupyter/src/app/pages/volume-details-page/overview/link-groups-table/link-groups-table.component.html
frontend/jupyter/src/app/pages/volume-details-page/overview/link-groups-table/link-groups-table.component.scss
frontend/jupyter/src/app/pages/volume-details-page/overview/link-groups-table/link-groups-table.component.spec.ts
frontend/jupyter/src/app/pages/volume-details-page/overview/link-groups-table/link-groups-table.component.ts
frontend/jupyter/src/app/pages/volume-details-page/overview/link-groups-table/link-groups-table.module.ts
frontend/jupyter/src/app/pages/volume-details-page/overview/link-groups-table/types.ts
frontend/jupyter/src/app/pages/volume-details-page/overview/overview.component.html
frontend/jupyter/src/app/pages/volume-details-page/overview/overview.component.spec.ts
frontend/jupyter/src/app/pages/volume-details-page/overview/overview.component.ts
frontend/jupyter/src/app/pages/volume-details-page/overview/overview.module.ts
frontend/jupyter/src/app/pages/volume-details-page/overview/pod-groups-mock.ts
frontend/jupyter/src/app/pages/volume-details-page/overview/pods-mock.ts
frontend/jupyter/src/app/pages/volume-details-page/pvc-mock.ts
frontend/jupyter/src/app/pages/volume-details-page/volume-details-page.component.html
frontend/jupyter/src/app/pages/volume-details-page/volume-details-page.component.spec.ts
frontend/jupyter/src/app/pages/volume-details-page/volume-details-page.component.ts
frontend/jupyter/src/app/pages/volume-details-page/volume-details-page.module.ts
frontend/jupyter/src/app/pages/volume-details-page/yaml/yaml.component.html
frontend/jupyter/src/app/pages/volume-details-page/yaml/yaml.component.spec.ts
frontend/jupyter/src/app/pages/volume-details-page/yaml/yaml.component.ts
frontend/jupyter/src/app/pages/volume-details-page/yaml/yaml.module.ts

For https://github.com/StatCan/jupyter-apis/issues/231
Adds the new volume-details-page

KF1.7 - add volume-details-page

---

frontend/jupyter/src/app/app-routing.module.ts
frontend/jupyter/src/app/app.module.ts
frontend/jupyter/src/app/pages/form/form-new/volume/existing/pvc/pvc.component.spec.ts
frontend/jupyter/src/app/pages/form/form-new/volume/existing/pvc/pvc.component.ts
frontend/jupyter/src/app/pages/index/columns/columns.module.ts
frontend/jupyter/src/app/pages/index/columns/delete-button/delete-button.component.html
frontend/jupyter/src/app/pages/index/columns/delete-button/delete-button.component.spec.ts
frontend/jupyter/src/app/pages/index/columns/delete-button/delete-button.component.ts
frontend/jupyter/src/app/pages/index/columns/used-by/used-by.component.html
frontend/jupyter/src/app/pages/index/columns/used-by/used-by.component.scss
frontend/jupyter/src/app/pages/index/columns/used-by/used-by.component.spec.ts
frontend/jupyter/src/app/pages/index/columns/used-by/used-by.component.ts
frontend/jupyter/src/app/pages/index/config.ts
frontend/jupyter/src/app/pages/index/index-default/config.ts
frontend/jupyter/src/app/pages/index/index-default/index-default.component.ts
frontend/jupyter/src/app/pages/index/index.component.spec.ts
frontend/jupyter/src/app/pages/volume-form/volume-form.component.html
frontend/jupyter/src/app/pages/volume-form/volume-form.component.spec.ts
frontend/jupyter/src/app/pages/volume-form/volume-form.component.ts
frontend/jupyter/src/app/services/actions.service.ts
frontend/jupyter/src/app/services/backend.service.ts
frontend/jupyter/src/app/types/responses.ts
frontend/jupyter/src/app/types/volume/interfaces.ts

closes https://github.com/StatCan/aaw/issues/1706

Kf1.7 volume table stuff

---

frontend/jupyter/src/app/pages/form/form-new/form-cpu-ram/form-cpu-ram.component.ts
frontend/jupyter/src/app/pages/form/form-new/form-new.component.html

For https://github.com/StatCan/aaw/issues/1770
I tested with my own test namespace "mathis-test" by adding the learning label through the jsonnet.
Whoever reviews and wants to test can either add the label(in the issue for the actual label) or just ask to be added as a contributor to my namespace.

added learning namespace max allowed limits

---

frontend/jupyter/src/app/pages/form/form-new/form-cpu-ram/form-cpu-ram.component.ts
frontend/jupyter/src/app/pages/form/form-new/form-gpus/form-gpus.component.ts
frontend/jupyter/src/app/pages/form/form-new/form-new.component.html

closes https://github.com/StatCan/aaw/issues/1776

feat(gpu): deny gpu for learning workspace

---

notebooks.go

closes https://github.com/StatCan/jupyter-apis/issues/269

fixed bug with gpu input

---

frontend/common/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/paginator/custom-paginator-intl.ts
frontend/common/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/resource-table.module.ts
frontend/jupyter/i18n/fr/messages.fr.xlf
frontend/jupyter/i18n/messages.xlf

closes https://github.com/StatCan/jupyter-apis/issues/271

added i18n to paginator

---

.github/workflows/publish.yml

must determine when to quit out

feat(workflows): integrate dockle

---

frontend/jupyter/i18n/fr/messages.fr.xlf
frontend/jupyter/i18n/messages.xlf
frontend/jupyter/src/app/pages/form/form-new/form-data-volumes/form-data-volumes.component.html
frontend/jupyter/src/app/pages/form/form-new/form-data-volumes/form-data-volumes.component.ts
frontend/jupyter/src/app/pages/form/form-new/form-workspace-volume/form-workspace-volume.component.html
frontend/jupyter/src/app/pages/form/form-new/form-workspace-volume/form-workspace-volume.component.ts
frontend/jupyter/src/app/pages/form/form-new/utils.ts
frontend/jupyter/src/app/pages/form/form-new/volume/mount/mount.component.html
frontend/jupyter/src/app/pages/form/form-new/volume/mount/mount.component.ts
frontend/jupyter/src/app/pages/form/form-new/volume/new/name/name.component.ts
frontend/jupyter/src/app/shared/utils/volumes/forms.ts

closes https://github.com/StatCan/jupyter-apis/issues/215

add duplicate mount path validation

---

frontend/jupyter/i18n/fr/messages.fr.xlf
frontend/jupyter/i18n/messages.xlf
frontend/jupyter/src/app/pages/form/form-new/form-image-custom/form-image-custom.component.html

closes https://github.com/StatCan/aaw/issues/369

added custom image message

---

frontend/common/kubeflow-common-lib/projects/kubeflow/src/lib/services/namespace.service.ts
frontend/jupyter/src/app/pages/form/form-new/form-new.component.ts
frontend/jupyter/src/app/pages/notebook-page/notebook-page.component.ts
frontend/jupyter/src/app/pages/volume-details-page/volume-details-page.component.ts

closes https://github.com/StatCan/jupyter-apis/issues/258

namespace change url bug

---

frontend/jupyter/i18n/fr/messages.fr.xlf
frontend/jupyter/i18n/messages.xlf
frontend/jupyter/src/app/pages/form/form-new/form-image-custom/form-image-custom.component.ts
frontend/jupyter/src/app/pages/form/form-new/volume/existing/pvc/pvc.component.ts

closes https://github.com/StatCan/jupyter-apis/issues/284

added messages for required validation

---

frontend/jupyter/i18n/fr/messages.fr.xlf
frontend/jupyter/i18n/messages.xlf
frontend/jupyter/src/app/pages/form/form-new/form-protected-b/form-protected-b.component.ts
frontend/jupyter/src/app/pages/form/form-new/volume/existing/pvc/pvc.component.html
frontend/jupyter/src/app/pages/form/form-new/volume/existing/pvc/pvc.component.spec.ts
frontend/jupyter/src/app/pages/form/form-new/volume/existing/pvc/pvc.component.ts

Closes https://github.com/StatCan/aaw-private/issues/24

Validate the volumes

---

frontend/jupyter/cypress/e2e/form-page.cy.ts
frontend/jupyter/cypress/e2e/main-page.cy.ts
frontend/jupyter/i18n/fr/messages.fr.xlf
frontend/jupyter/i18n/messages.xlf
frontend/jupyter/package-lock.json
frontend/jupyter/package.json
frontend/jupyter/src/app/pages/volume-details-page/overview/overview.component.spec.ts
frontend/jupyter/src/app/pages/volume-details-page/pvc-mock.ts
frontend/jupyter/src/app/pages/volume-details-page/volume-details-page.component.spec.ts
frontend/jupyter/src/app/pages/volume-details-page/volume-details-page.component.ts
frontend/jupyter/src/app/services/backend.service.ts
frontend/jupyter/src/app/types/responses.ts
frontend/jupyter/src/app/types/volume/interfaces.ts
frontend/jupyter/yarn.lock
persistentvolumeclaims.go

closes https://github.com/StatCan/jupyter-apis/issues/283
I had to update cypress version. There was an issue that was failing the github action that runs our cypress tests. Updating the version should fix it.

Volume details delete button

---

frontend/jupyter/cypress/e2e/main-page.cy.ts
frontend/jupyter/i18n/fr/messages.fr.xlf
frontend/jupyter/src/app/pages/index/index-default/index-default.component.html
frontend/jupyter/src/app/pages/index/index-default/index-default.component.ts

Closes https://github.com/StatCan/jupyter-apis/issues/257
Need to figure out how to test

Feat spinner

---

notebooks.go

closes https://github.com/StatCan/jupyter-apis/issues/288

added trimSpace to image value

---

frontend/jupyter/src/app/pages/form/form-new/form-configurations/form-configurations.component.html
frontend/jupyter/src/app/pages/form/form-new/form-configurations/form-configurations.component.ts

Closes https://github.com/StatCan/aaw/issues/1848
Part 3/3

Show configuration IF they exist

---

frontend/jupyter/i18n/fr/messages.fr.xlf
frontend/jupyter/i18n/messages.xlf
frontend/jupyter/src/app/pages/index/columns/delete-button/delete-button.component.html
frontend/jupyter/src/app/pages/index/columns/delete-button/delete-button.component.ts
frontend/jupyter/src/app/pages/index/index-default/index-default.component.ts

closes https://github.com/StatCan/jupyter-apis/issues/282

updated pvc delete button hover text

---

frontend/jupyter/cypress/e2e/volume-details-page.cy.ts
frontend/jupyter/i18n/fr/messages.fr.xlf
frontend/jupyter/i18n/messages.xlf
frontend/jupyter/src/app/pages/volume-details-page/overview/overview.component.html
frontend/jupyter/src/app/pages/volume-details-page/overview/overview.component.ts
frontend/jupyter/src/app/pages/volume-details-page/overview/overview.module.ts
frontend/jupyter/src/app/pages/volume-details-page/volume-details-page.component.html
frontend/jupyter/src/app/pages/volume-details-page/volume-details-page.component.ts

closes https://github.com/StatCan/jupyter-apis/issues/290

Display attached notebooks in volume details page

---

frontend/jupyter/src/app/pages/form/form-new/form-protected-b/form-protected-b.component.ts

closes https://github.com/StatCan/jupyter-apis/issues/301

fixed prob checkbox bug

---

frontend/jupyter/cypress/e2e/form-page.cy.ts
frontend/jupyter/src/app/pages/form/form-new/form-data-volumes/form-data-volumes.component.html
frontend/jupyter/src/app/pages/form/form-new/form-data-volumes/form-data-volumes.component.ts
frontend/jupyter/src/app/pages/form/form-new/form-workspace-volume/form-workspace-volume.component.html
frontend/jupyter/src/app/pages/form/form-new/form-workspace-volume/form-workspace-volume.component.ts

Closes https://github.com/StatCan/aaw/issues/1782

Open new item

---

frontend/jupyter/src/app/pages/form/form-new/form-configurations/form-configurations.component.ts
poddefaults.go

Part 2 of https://github.com/StatCan/aaw/issues/1871

Block protected b label from configs

---

frontend/jupyter/src/app/pages/form/form-new/form-new.component.ts
main.go
notebooks.go

closes https://github.com/StatCan/aaw/issues/1921

Create default notebook 2.0

---

.github/workflows/publish.yml
Taskfile.yml

for https://github.com/StatCan/aaw-private/issues/159 and https://jirab.statcan.ca/browse/BTIS-88

update jupyter image to build 2.0

---

main.go
notebooks.go

Part of Jira https://jirab.statcan.ca/browse/BTIS-77 to show the default notebook

Add /default api

---

main.go

We wanted a more appropriate name. 
Part of https://jirab.statcan.ca/browse/BTIS-95

Edit Create Default API

---

.github/workflows/build.yml
.github/workflows/publish.yml

See https://jirab.statcan.ca/browse/BTIS-93

Add the 2.0 branch 2

---

notebooks.go

To try to fix an issue from https://jirab.statcan.ca/browse/BTIS-112

added error handling if no default notebook found

---

notebooks.go

to replace 500 with 404 status code in cases where no default notebook is found

updated return code for no default notebook

---

frontend/jupyter/cypress/e2e/form-page.cy.ts
frontend/jupyter/cypress/e2e/main-page.cy.ts
frontend/jupyter/cypress/e2e/notebook-details-page.cy.ts
frontend/jupyter/cypress/e2e/volume-details-page.cy.ts
frontend/jupyter/cypress/support/commands.ts
frontend/jupyter/cypress/support/e2e.ts
frontend/jupyter/i18n/fr/messages.fr.xlf
frontend/jupyter/i18n/messages.xlf
frontend/jupyter/src/app/pages/index/index-default/config.ts
frontend/jupyter/src/app/pages/index/index-default/default-icon/default-icon.component.html
frontend/jupyter/src/app/pages/index/index-default/default-icon/default-icon.component.ts
frontend/jupyter/src/app/pages/index/index-default/index-default.component.ts
frontend/jupyter/src/app/pages/index/index.module.ts
frontend/jupyter/src/app/types/notebook.ts

https://jirab.statcan.ca/browse/BTIS-139
Local image

Add icon for default notebook

---

config.go
frontend/jupyter/cypress/e2e/form-page.cy.ts
frontend/jupyter/cypress/fixtures/config.json
frontend/jupyter/src/app/pages/form/form-new/form-image-custom/form-image-custom.component.html
frontend/jupyter/src/app/pages/form/form-new/form-image-custom/form-image-custom.component.spec.ts
frontend/jupyter/src/app/pages/form/form-new/form-image-custom/form-image-custom.component.ts
frontend/jupyter/src/app/pages/form/form-new/form-image/form-image.component.html
frontend/jupyter/src/app/pages/form/form-new/form-image/form-image.component.spec.ts
frontend/jupyter/src/app/pages/form/form-new/form-image/form-image.component.ts
frontend/jupyter/src/app/pages/form/form-new/form-new.component.html
frontend/jupyter/src/app/pages/form/form-new/form-new.component.ts
frontend/jupyter/src/app/pages/form/form-new/utils.ts
frontend/jupyter/src/app/types/config.ts
frontend/jupyter/src/app/types/notebook.ts
samples/spawner_ui_config.yaml

Related to https://jirab.statcan.ca/browse/BTIS-193

Remove all image one and image three ref

---

frontend/jupyter/package-lock.json
frontend/jupyter/package.json
frontend/jupyter/yarn.lock
notebooks.go
samples/spawner_ui_config.yaml

fixes https://jirab.statcan.ca/browse/BTIS-270

added fix to enumerate duplicate names in default notebook creation

---

frontend/jupyter/src/app/pages/form/form-new/form-cpu-ram/form-cpu-ram.component.ts

https://jirab.statcan.ca/browse/BTIS-603
We can change the default but we need to also make this change to pass validation

chore(zone-dev): update minimum req

---

frontend/jupyter/cypress/e2e/form-page.cy.ts
frontend/jupyter/src/app/pages/form/form-new/form-cpu-ram/form-cpu-ram.component.html
frontend/jupyter/src/app/pages/form/form-new/form-cpu-ram/form-cpu-ram.component.ts

https://jirab.statcan.ca/browse/BTIS-603

chore(limit): modify as well

---

frontend/jupyter/cypress/e2e/form-page.cy.ts
frontend/jupyter/cypress/e2e/notebook-details-page.cy.ts
frontend/jupyter/cypress/fixtures/notebook.json
frontend/jupyter/src/app/pages/form/form-new/form-cpu-ram/form-cpu-ram.component.html
frontend/jupyter/src/app/pages/form/form-new/form-cpu-ram/form-cpu-ram.component.ts
frontend/jupyter/src/app/pages/form/form-new/form-new.component.ts

https://jirab.statcan.ca/browse/BTIS-841

feat(jupyter): Remove limits for UI

---

frontend/common/kubeflow-common-lib/package-lock.json
frontend/common/kubeflow-common-lib/package.json
frontend/jupyter/package-lock.json
frontend/jupyter/package.json
frontend/jupyter/yarn.lock

for https://jirab.statcan.ca/browse/BTIS-672

fix: removed vulnerabilities for common-lib and jupyter

---

frontend/common/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/table/table.component.html
frontend/jupyter/i18n/fr/messages.fr.xlf
frontend/jupyter/i18n/messages.xlf
frontend/jupyter/src/app/pages/form/form-new/form-image/form-image.component.html

Ticket: https://jirab.statcan.ca/browse/BTIS-901

Fix i18n for aria-labels

---

README.md
events.go
main.go
notebooks.go
persistentvolumeclaims.go
rest-tests/restclient.http
samples/spawner_ui_config.yaml
status.go
viewer.go

for https://jirab.statcan.ca/browse/BTIS-659
Tested by:
1. Running the backend locally, and proxying to kubecost as mentioned in the README
2. Going through all our defined http rest client calls under ./rest-tests
The only ones not working/tests are the PVC related ones (outside of the "delete PVC" one that i tested). This is because KF1.9 introduced this new CRD named PVCViewer, but we don't currently have that CRD on our cluster. So these functions will be tested in another ticket when we have all the components in place.

update(backend): update jupyter-apis backend for KF1.9
